<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LOKGKB2" failures="0" tests="5" name="com.OpenCart.TestCases.T3_HomePageTest" time="0.004" errors="1" timestamp="2025-09-09T16:03:25 IST" skipped="4">
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="pageSetup" time="0.002">
    <error message="Cannot invoke &quot;com.OpenCart.Pages.P2_LoginPage.doLogin(String, String)&quot; because &quot;this.lp&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.OpenCart.Pages.P2_LoginPage.doLogin(String, String)" because "this.lp" is null
at com.OpenCart.TestCases.T3_HomePageTest.pageSetup(T3_HomePageTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- pageSetup -->
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="verifyProductCount" time="0.000">
    <skipped/>
  </testcase> <!-- verifyProductCount -->
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="verifyProductDetails" time="0.002">
    <skipped/>
  </testcase> <!-- verifyProductDetails -->
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="validateAddToCart" time="0.000">
    <skipped/>
  </testcase> <!-- validateAddToCart -->
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="verifyCartPageLaunch" time="0.000">
    <skipped/>
  </testcase> <!-- verifyCartPageLaunch -->
</testsuite> <!-- com.OpenCart.TestCases.T3_HomePageTest -->
